name: Designers against AIDS
favicon: null
layout_spectrum: 0.89062
typography_spectrum: 0.7622252441942692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#b4b9bc'
    - '#a0214c'
    - '#2d2522'
    - '#d3468a'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.35756372357718647
  rhythmicContrast: 0.8232262695673853
purpose: []
