name: Designers against AIDS
favicon: null
layout_spectrum: 0.8748225846793503
typography_spectrum: 0.7622252441942692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.33182584727182984
  lightness: 0.5160263141151518
  saturation: 0.35756372357718647
  rhythmicContrast: 0.8232262695673853
purpose: []
