name: Designers against AIDS
favicon: null
layout_spectrum: 0.89062
typography_spectrum: 0.7622252441942692
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d32b12'
    - '#a9965f'
    - '#fdfef0'
    - '#433b29'
  brandStrength: 0.4375
  lightness: 0.5
  saturation: 0.35756372357718647
  rhythmicContrast: 0.8232262695673853
purpose: []
